#!/bin/bash
apt clean
apt autoclean
sed -i '/^\([^#].*main\)*$/s/main/& contrib non-free-firmware/' /etc/apt/sources.list
apt-get update
apt-get install sudo xz-utils whiptail wget unzip xserver-xorg xinit fluxbox lxpolkit thunar thunar-archive-plugin udevil volumeicon-alsa alsa-utils slim blackbird-gtk-theme paper-icon-theme  network-manager-gnome conky qutebrowser firmware-linux-nonfree firmware-misc-nonfree firmware-realtek firmware-atheros firmware-iwlwifi firmware-brcm80211 firmware-amd-graphics firmware-b43-installer firmware-b43legacy-installer apulse arandr -y
apt-get install --no-install-recommends synaptic gparted featherpad lxappearance sakura scrot mate-power-manager xarchiver -y
rm -rf /usr/share/fluxbox/styles
sed -i 's/false/true/' /etc/NetworkManager/NetworkManager.conf
sed -i 's/Devuan/Fluxuan/' /etc/motd
sed -i 's/Debian/Fluxuan/' /etc/motd
sed -i 's/Devuan/Fluxuan/' /etc/issue
sed -i 's/Debian/Fluxuan/' /etc/issue
sed -i 's/Devuan/Fluxuan/' /etc/issue.net
sed -i 's/Debian/Fluxuan/' /etc/issue.net
sed -i 's/Devuan/Fluxuan/' /etc/os-release
sed -i 's/Debian/Fluxuan/' /etc/os-release
sed -i 's/devuan/Fluxuan/' /etc/os-release
sed -i 's/Devuan/Fluxuan/' /usr/lib/os-release
sed -i 's/Debian/Fluxuan/' /usr/lib/os-release
sed -i 's/devuan/Fluxuan/' /usr/lib/os-release
sed -i 's/Devuan/Fluxuan/' /usr/lib/os-release
echo "vm.vfs_cache_pressure = 50" >> /etc/sysctl.d/fluxuanctl.conf
echo "kernel.kptr_restrict=1" >> /etc/sysctl.d/fluxuanctl.conf
echo "net.core.bpf_jit_harden=2" >> /etc/sysctl.d/fluxuanctl.conf
echo "dev.tty.ldisc_autoload=0" >> /etc/sysctl.d/fluxuanctl.conf
echo "vm.unprivileged_userfaultfd=0" >> /etc/sysctl.d/fluxuanctl.conf
echo "kernel.kexec_load_disabled=1" >> /etc/sysctl.d/fluxuanctl.conf
echo "kernel.yama.ptrace_scope=2" >> /etc/sysctl.d/fluxuanctl.conf
echo "vm.mmap_rnd_bits=32" >> /etc/sysctl.d/fluxuanctl.conf
echo "vm.mmap_rnd_compat_bits=16" >> /etc/sysctl.d/fluxuanctl.conf
echo "fs.protected_fifos=2" >> /etc/sysctl.d/fluxuanctl.conf
echo "fs.protected_regular=2" >> /etc/sysctl.d/fluxuanctl.conf
echo "net.ipv4.conf.all.rp_filter=1" >> /etc/sysctl.d/fluxuanctl.conf
echo "net.ipv4.conf.default.rp_filter=1" >> /etc/sysctl.d/fluxuanctl.conf
curl -LJO raw.githubusercontent.com/crentz/fx/main/mmaker.deb
apt install ./mmaker.deb -y
rm -rf mmaker.deb
touch /etc/apt/apt.conf.d/80updatehook
echo "DPkg::Post-Invoke {"fxmenuupdate";};" >> /etc/apt/apt.conf.d/80updatehook
cd /etc/skel
curl -LJO raw.githubusercontent.com/crentz/fx/main/fx.tar.xz
tar -xf fx.tar.xz
rm -rf fx.tar.xz
chmod +x fxmenuupdate fwel widevine fluxuan-installer
mv fxmenuupdate fwel widevine fluxuan-installer /usr/bin/
mv fxslim /usr/share/slim/themes/
mv fx /usr/share/
echo "fluxuan ALL=(ALL) NOPASSWD: /usr/bin/fluxuan-installer" >> /etc/sudoers
mv 40-libinput.conf /etc/X11/xorg.conf.d/
mv slim.conf /etc/
cd
rm -rf fxi
find /usr/share/doc -depth -type f | xargs rm || true
rm -rf /usr/share/man/* /usr/share/groff/* /usr/share/info/* /usr/share/lintian/* /usr/share/linda/* /var/cache/man/*
apt-get clean
apt-get autoclean
apt-get autoremove
echo "Everything installed / All finished !!!"
