#!/bin/bash
apt-get update
apt-get install sudo xz-utils whiptail wget unzip xserver-xorg xinit  fluxbox lxpolkit thunar thunar-archive-plugin udevil volumeicon-alsa alsa-utils slim blackbird-gtk-theme network-manager-gnome conky qutebrowser firmware-linux-nonfree firmware-misc-nonfree firmware-realtek firmware-atheros firmware-iwlwifi firmware-brcm80211 firmware-amd-graphics firmware-b43-installer firmware-b43legacy-installer apulse arandr -y -qq
apt-get install --no-install-recommends net-tools isc-dhcp-client synaptic gparted featherpad squashfs-tools nano lxappearance scrot xarchiver -y -qq
rm -rf /usr/share/fluxbox/styles
sed -i 's/Devuan/Fluxuan/g; s/Debian/Fluxuan/g; s/devuan/Fluxuan/g' /etc/motd /etc/issue /etc/issue.net /etc/os-release /usr/lib/os-release
curl -LJO raw.githubusercontent.com/crentz/fx/main/mmaker.deb
apt-get install ./mmaker.deb -y -qq
rm -rf mmaker.deb
cd /etc/skel
curl -LJO raw.githubusercontent.com/crentz/fx/main/fx.tar.xz
tar -xf fx.tar.xz
rm -rf fx.tar.xz
chmod +x fxmenuupdate fwel widevine fluxuan-installer
mv fxmenuupdate fwel widevine fluxuan-installer /usr/bin/
mv fx /usr/share/
mv fxslim /usr/share/slim/themes/
echo "fluxuan ALL=(ALL) NOPASSWD: /usr/bin/fluxuan-installer" >> /etc/sudoers
mv 40-libinput.conf /etc/X11/xorg.conf.d/
touch /etc/apt/apt.conf.d/80updatehook
echo "DPkg::Post-Invoke {"fxmenuupdate";};" >> /etc/apt/apt.conf.d/80updatehook
cd
rm -rf fxi
sed -i 's/current_theme.*/current_theme fxslim/' /etc/slim.conf
sed -i 's/^#auto_login[[:space:]]*no/auto_login yes/' /etc/slim.conf
sed -i 's/^#default_user[[:space:]]*simone/default_user fluxuan/' /etc/slim.conf
find /usr/share/locale -mindepth 1 -maxdepth 1 -type d ! -name 'en*' -exec rm -rf {} \;
apt-get remove --purge zutty -y
update-alternatives --set x-terminal-emulator /usr/bin/xterm
apt-get autoremove -y
apt-get clean
apt-get autoclean
apt-get autoremove
echo "Everything installed / All finished !!!"
