#!/bin/bash


############################
#     Packages to Install
############################
echo "Cleaning and installing needed packages, please wait.... !!!!" ;
apt clean ;
apt autoclean ;
sed -i '/^\([^#].*main\)*$/s/main/& contrib non-free-firmware/' /etc/apt/sources.list ;
apt-get update && apt-get upgrade -y -qq ;
apt-get install sudo \
xz-utils \
wget \
unzip \
xserver-xorg \
xinit \
fluxbox \
lxpolkit \
pcmanfm \
udevil \
xcompmgr \
wbar \
volumeicon-alsa \
alsa-utils \
slim \
yad \
blackbird-gtk-theme \
paper-icon-theme \
firmware-linux-nonfree \
firmware-misc-nonfree \
firmware-realtek \
firmware-atheros \
firmware-iwlwifi \
firmware-brcm80211 \
firmware-amd-graphics \
firmware-b43-installer \
firmware-b43legacy-installer \
network-manager-gnome -y -qq >/dev/null ;
apt-get install --no-install-recommends synaptic \
gparted \
featherpad \
lxappearance \
viewnior \
sakura \
scrot \
gufw \
firefox-esr \
mate-power-manager \
xarchiver -y -qq ;
usermod -aG sudo fluxuan ;
sed -i 's/false/true/' /etc/NetworkManager/NetworkManager.conf ;
rm -rf /usr/share/fluxbox/styles ;
sed -i 's/Devuan/Fluxuan/' /etc/motd ;
sed -i 's/Debian/Fluxuan/' /etc/motd ;
sed -i 's/Devuan/Fluxuan/' /etc/issue ;
sed -i 's/Debian/Fluxuan/' /etc/issue ;
sed -i 's/Devuan/Fluxuan/' /etc/issue.net ;
sed -i 's/Debian/Fluxuan/' /etc/issue.net ;
sed -i 's/Devuan/Fluxuan/' /etc/os-release ;
sed -i 's/Debian/Fluxuan/' /etc/os-release ;
sed -i 's/devuan/Fluxuan/' /etc/os-release ;
sed -i 's/Devuan/Fluxuan/' /usr/lib/os-release ;
sed -i 's/Debian/Fluxuan/' /usr/lib/os-release ;
sed -i 's/devuan/Fluxuan/' /usr/lib/os-release ;
echo "vm.swappiness = 10" >>  /etc/sysctl.d/fluxuanctl.conf ;
echo "vm.dirty_ratio = 40" >>  /etc/sysctl.d/fluxuanctl.conf ;
echo "vm.dirty_background_ratio = 20" >>  /etc/sysctl.d/fluxuanctl.conf ;
echo "vm.vfs_cache_pressure = 50" >> /etc/sysctl.d/fluxuanctl.conf ;
curl -LJO raw.githubusercontent.com/crentz/fx/main/mmaker.deb ;
apt install ./mmaker.deb -y -qq ;
rm -rf mmaker.deb ;
touch /etc/apt/apt.conf.d/80updatehook ;
echo "DPkg::Post-Invoke {"fxmenuupdate";};" >> /etc/apt/apt.conf.d/80updatehook ;
rm -rf /usr/share/desktop-base ;
cd /etc/skel/ ;
curl -LJO raw.githubusercontent.com/crentz/fx/main/fxi.tar.xz ;
tar -xf fxi.tar.xz ;
rm -rf fxi.tar.xz ;
chmod +x Byef welcome fbscreensize fxmenuupdate fluxuan-installer fluxuan-snapshot ;
mv fxslim /usr/share/slim/themes/;
sed -i 's/desktop-slim-theme/fxslim/' /etc/slim.conf ;
sed -i 's/#default_user        simone/default_user fluxuan/' /etc/slim.conf ;
sed -i 's/#auto_login          no/auto_login yes/' /etc/slim.conf ;
echo "fluxuan ALL=(ALL) NOPASSWD: /usr/bin/fluxuan-installer" >> /etc/sudoers ;
mv fbscreensize fxmenuupdate Byef welcome fluxuan-installer fluxuan-snapshot /usr/bin/ ;
mv 40-libinput.conf /etc/X11/xorg.conf.d/ ;
mv fx /usr/share/ ;
mv start.wav /usr/share/sounds/ ;
rm -rf /boot/grub/splash.png ;
sed -i 's/GRUB_TIMEOUT=5/GRUB_TIMEOUT=3/' /etc/default/grub ;
sed -i 's/GRUB_THEME/#GRUB_THEME/' /etc/default/grub ;
sed -i 's/Devuan/Fluxuan/' /etc/default/grub ;
sed -i 's/Debian/Fluxuan/' /etc/default/grub ;
cp /usr/share/fx/splash.png /boot/grub/ ;
update-grub ;
apt clean ;
apt autoclean ;
apt update ;
cp -R .config/ .fluxbox/ .gtkrc-2.0 .fehbg .profile .bashrc .wbar /home/fluxuan/ ;
cd ;
rm -rf fxn ;
chown -R fluxuan:fluxuan /home/fluxuan/ ;
echo "####################################################" ;
echo "Packages finished and installed succesfully. Enjoy !" ;
echo "####################################################" ;
