#!/bin/bash


############################
#     Packages to Install
############################
echo "Cleaning and installing needed packages, please wait.... !!!!" ;
apt clean ;
apt autoclean ;
sed -i '/^\([^#].*main\)*$/s/main/& contrib non-free-firmware/' /etc/apt/sources.list ;
apt-get update && apt-get upgrade -y -qq ;
apt-get install sudo xz-utils wget unzip xserver-xorg xinit fluxbox lxpolkit pcmanfm udevil volumeicon-alsa alsa-utils slim blackbird-gtk-theme paper-icon-theme firmware-linux-nonfree firmware-misc-nonfree firmware-realtek firmware-atheros firmware-iwlwifi firmware-brcm80211 firmware-amd-graphics firmware-b43-installer firmware-b43legacy-installer network-manager-gnome -y -qq >/dev/null ;
apt-get install --no-install-recommends synaptic gparted featherpad lxappearance viewnior sakura scrot apulse mate-power-manager xarchiver -y -qq ;
rm -rf /usr/share/fluxbox/styles ;
sed -i 's/false/true/' /etc/NetworkManager/NetworkManager.conf ;
sed -i 's/Devuan/Fluxuan/' /etc/motd ;
sed -i 's/Debian/Fluxuan/' /etc/motd ;
sed -i 's/Devuan/Fluxuan/' /etc/issue ;
sed -i 's/Debian/Fluxuan/' /etc/issue ;
sed -i 's/Devuan/Fluxuan/' /etc/issue.net ;
sed -i 's/Debian/Fluxuan/' /etc/issue.net ;
sed -i 's/Devuan/Fluxuan/' /etc/os-release ;
sed -i 's/Debian/Fluxuan/' /etc/os-release ;
sed -i 's/devuan/Fluxuan/' /etc/os-release ;
sed -i 's/Devuan/Fluxuan/' /usr/lib/os-release ;
sed -i 's/Debian/Fluxuan/' /usr/lib/os-release ;
sed -i 's/devuan/Fluxuan/' /usr/lib/os-release ;
echo "vm.swappiness = 10" >>  /etc/sysctl.d/fluxuanctl.conf ;
echo "vm.dirty_ratio = 40" >>  /etc/sysctl.d/fluxuanctl.conf ;
echo "vm.dirty_background_ratio = 20" >>  /etc/sysctl.d/fluxuanctl.conf ;
echo "vm.vfs_cache_pressure = 50" >> /etc/sysctl.d/fluxuanctl.conf ;
echo "kernel.kptr_restrict=1" >> /etc/sysctl.d/fluxuanctl.conf ;
echo "net.core.bpf_jit_harden=2" >> /etc/sysctl.d/fluxuanctl.conf ;
echo "dev.tty.ldisc_autoload=0" >> /etc/sysctl.d/fluxuanctl.conf ;
echo "vm.unprivileged_userfaultfd=0" >> /etc/sysctl.d/fluxuanctl.conf ;
echo "kernel.kexec_load_disabled=1" >> /etc/sysctl.d/fluxuanctl.conf ;
echo "kernel.yama.ptrace_scope=2" >> /etc/sysctl.d/fluxuanctl.conf ;
echo "vm.mmap_rnd_bits=32" >> /etc/sysctl.d/fluxuanctl.conf ;
echo "vm.mmap_rnd_compat_bits=16" >> /etc/sysctl.d/fluxuanctl.conf ;
echo "fs.protected_fifos=2" >> /etc/sysctl.d/fluxuanctl.conf ;
echo "fs.protected_regular=2" >> /etc/sysctl.d/fluxuanctl.conf ;
echo "net.ipv4.conf.all.rp_filter=1" >> /etc/sysctl.d/fluxuanctl.conf ;
echo "net.ipv4.conf.default.rp_filter=1" >> /etc/sysctl.d/fluxuanctl.conf ;
curl -LJO raw.githubusercontent.com/crentz/fx/main/mmaker.deb ;
apt install ./mmaker.deb -y -qq ;
rm -rf mmaker.deb ;
touch /etc/apt/apt.conf.d/80updatehook ;
echo "DPkg::Post-Invoke {"fxmenuupdate";};" >> /etc/apt/apt.conf.d/80updatehook ;
rm -rf /usr/share/desktop-base ;
cd /etc/skel/ ;
curl -LJO raw.githubusercontent.com/crentz/fx/main/fxi.tar.xz ;
tar -xf fxi.tar.xz ;
rm -rf fxi.tar.xz ;
chmod +x .local/bin/*
mv fxslim /usr/share/slim/themes/;
sed -i 's/desktop-slim-theme/fxslim/' /etc/slim.conf ;
sed -i 's/#default_user        simone/default_user fluxuan/' /etc/slim.conf ;
sed -i 's/#auto_login          no/auto_login yes/' /etc/slim.conf ;
echo "fluxuan ALL=(ALL) NOPASSWD: /usr/bin/fluxuan-installer" >> /etc/sudoers ;
mv 40-libinput.conf /etc/X11/xorg.conf.d/ ;
rm -rf /boot/grub/splash.png ;
sed -i 's/GRUB_TIMEOUT=5/GRUB_TIMEOUT=3/' /etc/default/grub ;
sed -i 's/GRUB_THEME/#GRUB_THEME/' /etc/default/grub ;
sed -i 's/Devuan/Fluxuan/' /etc/default/grub ;
sed -i 's/Debian/Fluxuan/' /etc/default/grub ;
cp /usr/share/fx/splash.png /boot/grub/ ;
update-grub ;
apt clean ;
apt autoclean ;
rm -rf fxn ;
echo "####################################################" ;
echo "Packages finished and installed succesfully. Enjoy !" ;
echo "####################################################" ;
