#!/bin/bash


############################
#     Packages to Install
############################


if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi
apt clean ;
apt autoclean ;
apt remove --purge openssh-server \
vim-common \
vim-tiny \
mutt \
iamerican \
ibritish \
info \
ispell \
manpages \
vim-tiny \
vim-common \
w3m \
wamerican \
aspell \
bc \
dc \
dictionaries \
debian-faq \
debian-faq-de \
debian-faq-fr \
debian-faq-it \
debian-faq-zh-cn \
fdutils -y ;
apt autoremove -y ;
sed -i '/^\([^#].*main\)*$/s/main/& contrib non-free/' /etc/apt/sources.list ;
echo "Acquire::ForceIPv4 \"true\" ;" >> /etc/apt/apt.conf ;
echo "Acquire::Languages \"0\" ;" >> /etc/apt/apt.conf ;
touch  /etc/dpkg/dpkg.cfg.d/excludes ;
echo -e "path-exclude /usr/share/man/*\npath-exclude /usr/share/doc/*\npath-exclude /usr/share/doc-base/*\npath-exclude /usr/share/gtk-doc/*\npath-exclude /usr/share/help/*\npath-exclude /usr/share/info/*\npath-exclude /usr/share/man-db/*\npath-exclude /usr/share/groff/*\npath-exclude /usr/share/linda/*
\npath-exclude /usr/share/lintian/*" >> /etc/dpkg/dpkg.cfg.d/excludes ;
apt update && apt upgrade -y ;
apt install sudo \
wget \
unzip \
xserver-xorg \
xinit \
arandr \
fluxbox \
lxpolkit \
pcmanfm \
udevil \
alsa-utils \
xcompmgr \
volumeicon-alsa \
apulse \
wbar \
wbar-config \
yad \
slim \
xarchiver \
firmware-linux-nonfree \
firmware-misc-nonfree \
firmware-realtek \
firmware-atheros \
firmware-iwlwifi \
firmware-brcm80211 \
firmware-ralink \
firmware-b43-installer \
firmware-b43legacy-installer \
network-manager-gnome -y ;
usermod -aG sudo fluxuan ;
apt install --no-install-recommends synaptic \
gparted \
gufw \
featherpad \
lxappearance \
viewnior \
sakura \
xpaint \
scrot \
xpdf \
firefox-esr \
nitrogen \
bleachbit \
xarchiver -y ;
sed -i 's/false/true/' /etc/NetworkManager/NetworkManager.conf ;
rm -rf /usr/share/fluxbox/styles ;
sed -i 's/Devuan/Fluxuan/' /etc/motd ;
sed -i 's/Devuan/Fluxuan/' /etc/issue ;
sed -i 's/Devuan/Fluxuan/' /etc/issue.net ;
sed -i 's/Devuan/Fluxuan/' /etc/os-release ;
echo "vm.swappiness = 10" >>  /etc/sysctl.d/fluxuanctl.conf ;
echo "vm.dirty_ratio = 40" >>  /etc/sysctl.d/fluxuanctl.conf ;
echo "vm.dirty_background_ratio = 20" >>  /etc/sysctl.d/fluxuanctl.conf ;
echo "vm.vfs_cache_pressure = 50" >> /etc/sysctl.d/fluxuanctl.conf ;
echo "fluxuan ALL=(ALL:ALL) NOPASSWD: /usr/sbin/refractainstaller-wrapper.sh /usr/bin/refractainstaller-yad" >> /etc/sudoers ;
rm -rf /usr/share/desktop-base ;
cd /etc/skel/ ;
curl -LJO raw.githubusercontent.com/crentz/fx/main/fxn.zip ;
unzip fxn.zip ;
chmod +x CCP Byef fxw kyb ;
mv fxslim /usr/share/slim/themes/;
sed -i 's/desktop-slim-theme/fxslim/' /etc/slim.conf ;
sed -i 's/#default_user        simone/default_user fluxuan/' /etc/slim.conf ;
sed -i 's/#auto_login          no/auto_login yes/' /etc/slim.conf ;
mv kyb /usr/bin/ ;
mv CCP /usr/bin/ ;
mv Byef /usr/bin/ ;
mv fxw /usr/bin/ ;
touch /usr/bin/bbit ;
echo "!#/bin/bash" >> /usr/bin/bbit ;
echo "pkexec bleachbit" >> /usr/bin/bbit
chmod +x /usr/bin/bbit ;
mv wallpaper /usr/share/ ;
mv DarkArte /usr/share/themes/ ;
mv fx /usr/share/ ;
mv start.wav /usr/share/sounds/ ;
rm -rf fxn.zip ;
rm -rf /usr/share/doc/* ;
rm -rf /usr/share/doc-base/* ;
rm -rf /usr/share/gtk-doc/* ;
rm -rf /usr/share/help/* ;
rm -rf /usr/share/man-db/* ;
rm -rf /usr/share/man/* ;
rm -rf /usr/share/groff/* ;
rm -rf /usr/share/info/* ;
rm -rf /usr/share/lintian/* ;
rm -rf /usr/share/linda/* ;
rm -rf /var/cache/man/* ;
rm -rd /var/log/apt ;
rm -rd /var/cache/apt ;
apt clean ;
apt autoclean ;
apt update ;
cp -R .config/ .fluxbox/ .wbar .gtkrc-2.0 .screenlayout/ /home/fluxuan/ ;
cd ;
rm -rf fxn ;
cp /usr/share/applications/bleachbit-root.desktop /usr/share/fx/system/ ;
sed -i 's/pkexec bleachbit/bbit/' /usr/share/fx/system/bleachbit-root.desktop ;
chown -R fluxuan:fluxuan /home/fluxuan/ ;
apt remove --purge feh -y ;
apt autoremove -y ;
echo "Packages finished and installed succesfully. Enjoy !" ;
