#!/bin/bash

# Ensure the script is run as root
if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be run as root."
    exit 1
fi

# Remove unnecessary language packages
apt-get remove --purge -y $(dpkg-query -f '${binary:Package}\n' -W '*-locales' | grep -v '^libc6')

# Clean up unnecessary dependencies
apt-get autoremove --purge -y

# Clean package cache
apt-get clean

# Remove orphaned packages
deborphan | xargs apt-get -y remove --purge

# Remove old kernel versions
apt-get purge -y $(dpkg -l linux-{image,headers}-"[0-9]*" | awk '/ii/{print $2}' | grep -v "$(uname -r | sed 's/-amd64//')")

# Clean up APT cache
apt-get autoclean

# Remove unnecessary log files
find /var/log -type f -name "*.gz" -exec rm -f {} \;
find /var/log -type f -name "*.1" -exec rm -f {} \;

# Zero out free space to reduce the size of the final disk image
dd if=/dev/zero of=/EMPTY bs=1M
rm -f /EMPTY

echo "Reducing Deb based os completed. Reboot to apply changes."
